from datetime import date
from uuid import UUID

from sqlalchemy import (
    ARRAY,
    Computed,
    Date,
    ForeignKey,
    String,
    Text,
    Integer,
    UniqueConstraint,
    text,
    Index
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR

from app.models.assessment import Assessment
from app.models.base import Base, TimestampMixin, UUIDMixin
from app.models.case import Case
from app.models.finding_category import FindingCategory
from app.models.document import Document

class Finding(Base, TimestampMixin, UUIDMixin):
    """
    A single finding from a regulatory inspection
    Each finding belongs to one assessment (within a case),
    optionally references a category from the regulator's
    vocabulary, optionally points back to a source document, and 
    carries verbatim text plus optional summarization fields 
    poplulated downstream.
    """

    __tablename__ = "findings"
    
    # Core relationships
    assessment_id: Mapped[UUID] = mapped_column(
        ForeignKey("assessments.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Denormalized from assessments.case_id for query convenience.
    case_id: Mapped[UUID] = mapped_column(
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
    )

    category_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("finding_categories.id", ondelete="RESTRICT"),
        nullable=True,
    )

    source_document_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Position within the assessment (extractor-assigned, 1-based)
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)

    # Lifecycle dates
    identified_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    completed_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # Workflow / ownership
    state: Mapped[str | None] = mapped_column(String(50), nullable=True)
    person_responsible: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # The literal category string from the source document — a snapshot.
    # The category_id resolves to a FindingCategory row; this preserves
    # what the document actually said in case of normalization differences.
    category_raw: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Description: verbatim text from the source PDF. Source of truth.
    description_verbatim: Mapped[str] = mapped_column(Text, nullable=False)

    # Optional summarization fields, populated by a downstream LLM step.
    description_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    summary_bullets: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)

    # Semi-structured references extracted from the description text.
    # JSONB for objects, native array for flat URLs.
    referenced_standards: Mapped[list[dict] | None] = mapped_column(JSONB, nullable=True)
    referenced_urls: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)

    # Pages in the source PDF where this finding's content appears.
    source_page_numbers: Mapped[list[int] | None] = mapped_column(ARRAY(Integer), nullable=True)

    # Full-text search vector — generated by Postgres from description_verbatim.
    # English language analysis (stemming, stopwords, etc.). Update the
    # 'english' argument if you need different language handling.
    description_tsv: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', description_verbatim)", persisted=True),
        nullable=True,
    )

    # Relationships
    assessment: Mapped[Assessment] = relationship()
    case: Mapped[Case] = relationship()
    category: Mapped[FindingCategory | None] = relationship()
    source_document: Mapped[Document | None] = relationship()

    __table_args__ = (
        UniqueConstraint(
            "assessment_id", "ordinal",
            name="uq_finding_ordinal_per_assessment",
        ),
        # GIN index on the tsvector for fast full-text search.
        Index(
            "ix_findings_description_tsv",
            "description_tsv",
            postgresql_using="gin", # Generalized Inverted Index for full-text search
        ),
        # Indexes for common query patterns
        Index("ix_findings_case_id", "case_id"),
        Index("ix_findings_category_id", "category_id"),
    )
