"""create findings table

Revision ID: 6bd38bbfcee2
Revises: ca41b23ba8be
Create Date: 2026-04-30 02:07:22.463580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bd38bbfcee2'
down_revision: Union[str, Sequence[str], None] = 'ca41b23ba8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('identified_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('person_responsible', sa.String(length=255), nullable=True),
    sa.Column('category_raw', sa.String(length=255), nullable=True),
    sa.Column('description_verbatim', sa.Text(), nullable=False),
    sa.Column('description_summary', sa.Text(), nullable=True),
    sa.Column('summary_bullets', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('referenced_standards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('referenced_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_page_numbers', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column(
        'description_tsv',
        postgresql.TSVECTOR(),
        sa.Computed("to_tsvector('english', description_verbatim)", persisted=True),
        nullable=True
    ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['finding_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'ordinal', name='uq_finding_ordinal_per_assessment')
    )
    op.create_index('ix_findings_case_id', 'findings', ['case_id'], unique=False)
    op.create_index('ix_findings_category_id', 'findings', ['category_id'], unique=False)
    op.create_index('ix_findings_description_tsv', 'findings', ['description_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_description_tsv', table_name='findings', postgresql_using='gin')
    op.drop_index('ix_findings_category_id', table_name='findings')
    op.drop_index('ix_findings_case_id', table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
