"""create cases table and link documents

Revision ID: 6dbe9a577a79
Revises: db51a7e1beb1
Create Date: 2026-04-28 09:24:22.424358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbe9a577a79'
down_revision: Union[str, Sequence[str], None] = 'db51a7e1beb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('regulatory_body_id', sa.Uuid(), nullable=False),
    sa.Column('pharmacy_id', sa.Uuid(), nullable=True),
    sa.Column('consultant_id', sa.Uuid(), nullable=True),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('case_state', sa.String(length=50), nullable=True),
    sa.Column('case_closed_date', sa.Date(), nullable=True),
    sa.Column('licensee_name', sa.String(length=255), nullable=True),
    sa.Column('licensee_email', sa.String(length=255), nullable=True),
    sa.Column('consultant_assignment_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['inspectors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regulatory_body_id'], ['regulatory_bodies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulatory_body_id', 'case_number', name='uq_case_number_per_body')
    )
    op.add_column('documents', sa.Column('case_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_documents_case_id', 'documents', 'cases', ['case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_case_id', 'documents', type_='foreignkey')
    op.drop_column('documents', 'case_id')
    op.drop_table('cases')
    # ### end Alembic commands ###
