"""make jurisdiction nullable

Revision ID: 7a1c079591e3
Revises: 5f15e389a585
Create Date: 2026-04-27 11:09:38.822053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1c079591e3'
down_revision: Union[str, Sequence[str], None] = '5f15e389a585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regulatory_bodies', 'jurisdiction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regulatory_bodies', 'jurisdiction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
