"""create finding_categories table

Revision ID: ca41b23ba8be
Revises: 383b1486c0ae
Create Date: 2026-04-28 11:34:49.757498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca41b23ba8be'
down_revision: Union[str, Sequence[str], None] = '383b1486c0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_categories',
    sa.Column('regulatory_body_id', sa.Uuid(), nullable=False),
    sa.Column('full_path', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulatory_body_id'], ['regulatory_bodies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulatory_body_id', 'full_path', name='uq_category_path_per_body')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_categories')
    # ### end Alembic commands ###
