"""create documents table

Revision ID: db51a7e1beb1
Revises: 7a723d07086f
Create Date: 2026-04-28 08:12:56.627121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db51a7e1beb1'
down_revision: Union[str, Sequence[str], None] = '7a723d07086f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_hash', sa.String(length=80), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index('ix_documents_processing_status', 'documents', ['processing_status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_processing_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
